<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('country')->delete();

        $countries = array(
            array('name' => 'United States', 'code' => 'US', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Canada', 'code' => 'CA', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Afghanistan', 'code' => 'AF', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Albania', 'code' => 'AL', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Algeria', 'code' => 'DZ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'American Samoa', 'code' => 'AS', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Andorra', 'code' => 'AD', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Angola', 'code' => 'AO', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Anguilla', 'code' => 'AI', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Antarctica', 'code' => 'AQ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Antigua and/or Barbuda', 'code' => 'AG', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Argentina', 'code' => 'AR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Armenia', 'code' => 'AM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Aruba', 'code' => 'AW', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Australia', 'code' => 'AU', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Austria', 'code' => 'AT', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Azerbaijan', 'code' => 'AZ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Bahamas', 'code' => 'BS', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Bahrain', 'code' => 'BH', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Bangladesh', 'code' => 'BD', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Barbados', 'code' => 'BB', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Belarus', 'code' => 'BY', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Belgium', 'code' => 'BE', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Belize', 'code' => 'BZ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Benin', 'code' => 'BJ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Bermuda', 'code' => 'BM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Bhutan', 'code' => 'BT', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Bolivia', 'code' => 'BO', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Botswana', 'code' => 'BW', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Bouvet Island', 'code' => 'BV', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Brazil', 'code' => 'BR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'British lndian Ocean Territory', 'code' => 'IO', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Brunei Darussalam', 'code' => 'BN', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Bulgaria', 'code' => 'BG', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Burkina Faso', 'code' => 'BF', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Burundi', 'code' => 'BI', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Cambodia', 'code' => 'KH', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Cameroon', 'code' => 'CM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Cape Verde', 'code' => 'CV', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Cayman Islands', 'code' => 'KY', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Central African Republic', 'code' => 'CF', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Chad', 'code' => 'TD', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Chile', 'code' => 'CL', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'China', 'code' => 'CN', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Christmas Island', 'code' => 'CX', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Colombia', 'code' => 'CO', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Comoros', 'code' => 'KM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Congo', 'code' => 'CG', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Cook Islands', 'code' => 'CK', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Costa Rica', 'code' => 'CR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Croatia (Hrvatska)', 'code' => 'HR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Cuba', 'code' => 'CU', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Cyprus', 'code' => 'CY', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Czech Republic', 'code' => 'CZ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Democratic Republic of Congo', 'code' => 'CD', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Denmark', 'code' => 'DK', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Djibouti', 'code' => 'DJ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Dominica', 'code' => 'DM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Dominican Republic', 'code' => 'DO', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'East Timor', 'code' => 'TP', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Ecudaor', 'code' => 'EC', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Egypt', 'code' => 'EG', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'El Salvador', 'code' => 'SV', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Equatorial Guinea', 'code' => 'GQ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Eritrea', 'code' => 'ER', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Estonia', 'code' => 'EE', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Ethiopia', 'code' => 'ET', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Faroe Islands', 'code' => 'FO', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Fiji', 'code' => 'FJ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Finland', 'code' => 'FI', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'France', 'code' => 'FR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'France, Metropolitan', 'code' => 'FX', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'French Guiana', 'code' => 'GF', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'French Polynesia', 'code' => 'PF', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'French Southern Territories', 'code' => 'TF', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Gabon', 'code' => 'GA', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Gambia', 'code' => 'GM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Georgia', 'code' => 'GE', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Germany', 'code' => 'DE', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Ghana', 'code' => 'GH', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Gibraltar', 'code' => 'GI', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Greece', 'code' => 'GR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Greenland', 'code' => 'GL', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Grenada', 'code' => 'GD', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Guadeloupe', 'code' => 'GP', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Guam', 'code' => 'GU', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Guatemala', 'code' => 'GT', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Guinea', 'code' => 'GN', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Guinea-Bissau', 'code' => 'GW', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Guyana', 'code' => 'GY', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Haiti', 'code' => 'HT', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Heard and Mc Donald Islands', 'code' => 'HM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Honduras', 'code' => 'HN', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Hong Kong', 'code' => 'HK', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Hungary', 'code' => 'HU', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Iceland', 'code' => 'IS', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'India', 'code' => 'IN', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Indonesia', 'code' => 'ID', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Iran (Islamic Republic of)', 'code' => 'IR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Iraq', 'code' => 'IQ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Ireland', 'code' => 'IE', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Israel', 'code' => 'IL', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Italy', 'code' => 'IT', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Ivory Coast', 'code' => 'CI', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Jamaica', 'code' => 'JM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Japan', 'code' => 'JP', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Jordan', 'code' => 'JO', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Kazakhstan', 'code' => 'KZ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Kenya', 'code' => 'KE', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Kiribati', 'code' => 'KI', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Korea, Republic of', 'code' => 'KR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Kuwait', 'code' => 'KW', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Kyrgyzstan', 'code' => 'KG', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Lao People\'s Democratic Republic', 'code' => 'LA', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Latvia', 'code' => 'LV', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Lebanon', 'code' => 'LB', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Lesotho', 'code' => 'LS', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Liberia', 'code' => 'LR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Libyan Arab Jamahiriya', 'code' => 'LY', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Liechtenstein', 'code' => 'LI', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Lithuania', 'code' => 'LT', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Luxembourg', 'code' => 'LU', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Macau', 'code' => 'MO', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Macedonia', 'code' => 'MK', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Madagascar', 'code' => 'MG', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Malawi', 'code' => 'MW', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Malaysia', 'code' => 'MY', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Maldives', 'code' => 'MV', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Mali', 'code' => 'ML', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Malta', 'code' => 'MT', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Marshall Islands', 'code' => 'MH', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Martinique', 'code' => 'MQ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Mauritania', 'code' => 'MR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Mauritius', 'code' => 'MU', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Mayotte', 'code' => 'TY', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Mexico', 'code' => 'MX', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Micronesia, Federated States of', 'code' => 'FM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Moldova, Republic of', 'code' => 'MD', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Monaco', 'code' => 'MC', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Mongolia', 'code' => 'MN', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Montserrat', 'code' => 'MS', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Morocco', 'code' => 'MA', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Mozambique', 'code' => 'MZ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Myanmar', 'code' => 'MM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Namibia', 'code' => 'NA', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Nauru', 'code' => 'NR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Nepal', 'code' => 'NP', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Netherlands', 'code' => 'NL', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Netherlands Antilles', 'code' => 'AN', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'New Caledonia', 'code' => 'NC', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'New Zealand', 'code' => 'NZ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Nicaragua', 'code' => 'NI', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Niger', 'code' => 'NE', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Nigeria', 'code' => 'NG', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Niue', 'code' => 'NU', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Norfork Island', 'code' => 'NF', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Northern Mariana Islands', 'code' => 'MP', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Norway', 'code' => 'NO', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Oman', 'code' => 'OM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Pakistan', 'code' => 'PK', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Palau', 'code' => 'PW', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Panama', 'code' => 'PA', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Papua New Guinea', 'code' => 'PG', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Paraguay', 'code' => 'PY', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Peru', 'code' => 'PE', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Philippines', 'code' => 'PH', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Pitcairn', 'code' => 'PN', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Poland', 'code' => 'PL', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Portugal', 'code' => 'PT', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Puerto Rico', 'code' => 'PR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Qatar', 'code' => 'QA', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Republic of South Sudan', 'code' => 'SS', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Reunion', 'code' => 'RE', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Romania', 'code' => 'RO', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Russian Federation', 'code' => 'RU', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Rwanda', 'code' => 'RW', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Saint Lucia', 'code' => 'LC', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Samoa', 'code' => 'WS', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'San Marino', 'code' => 'SM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Sao Tome and Principe', 'code' => 'ST', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Saudi Arabia', 'code' => 'SA', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Senegal', 'code' => 'SN', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Serbia', 'code' => 'RS', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Seychelles', 'code' => 'SC', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Sierra Leone', 'code' => 'SL', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Singapore', 'code' => 'SG', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Slovakia', 'code' => 'SK', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Slovenia', 'code' => 'SI', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Solomon Islands', 'code' => 'SB', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Somalia', 'code' => 'SO', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'South Africa', 'code' => 'ZA', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'South Georgia South Sandwich Islands', 'code' => 'GS', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Spain', 'code' => 'ES', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Sri Lanka', 'code' => 'LK', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'St. Helena', 'code' => 'SH', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'St. Pierre and Miquelon', 'code' => 'PM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Sudan', 'code' => 'SD', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Suriname', 'code' => 'SR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Svalbarn and Jan Mayen Islands', 'code' => 'SJ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Swaziland', 'code' => 'SZ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Sweden', 'code' => 'SE', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Switzerland', 'code' => 'CH', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Syrian Arab Republic', 'code' => 'SY', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Taiwan', 'code' => 'TW', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Tajikistan', 'code' => 'TJ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Tanzania, United Republic of', 'code' => 'TZ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Thailand', 'code' => 'TH', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Togo', 'code' => 'TG', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Tokelau', 'code' => 'TK', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Tonga', 'code' => 'TO', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Trinidad and Tobago', 'code' => 'TT', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Tunisia', 'code' => 'TN', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Turkey', 'code' => 'TR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Turkmenistan', 'code' => 'TM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Turks and Caicos Islands', 'code' => 'TC', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Tuvalu', 'code' => 'TV', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Uganda', 'code' => 'UG', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Ukraine', 'code' => 'UA', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'United Arab Emirates', 'code' => 'AE', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'United Kingdom', 'code' => 'GB', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'United States minor outlying islands', 'code' => 'UM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Uruguay', 'code' => 'UY', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Uzbekistan', 'code' => 'UZ', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Vanuatu', 'code' => 'VU', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Vatican City State', 'code' => 'VA', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Venezuela', 'code' => 'VE', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Vietnam', 'code' => 'VN', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Virgin Islands (British)', 'code' => 'VG', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Virgin Islands (U.S.)', 'code' => 'VI', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Wallis and Futuna Islands', 'code' => 'WF', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Western Sahara', 'code' => 'EH', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Yemen', 'code' => 'YE', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Yugoslavia', 'code' => 'YU', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Zaire', 'code' => 'ZR', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Zambia', 'code' => 'ZM', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
            array('name' => 'Zimbabwe', 'code' => 'ZW', 'slug' => '', 'new_confirmed' => 0, 'total_confirmed' => 0, 'new_deaths' => 0, 'total_deaths' => 0, 'status_date' => null),
        );

        DB::table('country')->insert($countries);
    }
}
